const colors = {
  light: {
    text: '#191c1d',
    tint: '#006948',
    background: '#f8f9fa',
    foreground: '#191c1d',
    card: '#ffffff',
    cardForeground: '#191c1d',
    primary: '#006948',
    primaryForeground: '#ffffff',
    primaryContainer: '#00855d',
    primaryFixedDim: '#68dba9',
    secondary: '#575e70',
    secondaryForeground: '#ffffff',
    secondaryContainer: '#d9dff5',
    muted: '#f3f4f5',
    mutedForeground: '#6d7a72',
    surface: '#f8f9fa',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#f3f4f5',
    surfaceContainer: '#edeeef',
    surfaceContainerHigh: '#e7e8e9',
    surfaceContainerHighest: '#e1e3e4',
    onSurface: '#191c1d',
    onSurfaceVariant: '#3d4a42',
    outlineVariant: '#bccac0',
    outline: '#6d7a72',
    accent: '#f3f4f5',
    accentForeground: '#191c1d',
    destructive: '#ba1a1a',
    destructiveForeground: '#ffffff',
    border: '#bccac0',
    input: '#edeeef',
    error: '#ba1a1a',
  },
  radius: 16,
};

export default colors;
